### ISSUE TITLE
Syntax for Cuda?

### ISSUE THREAD

**Issue by Alexey-T** [NXP/JCShell-Tools#2]
Hello
Is it easy to make syntax lexer for SynWrite/ CudaText (one lexer is for 2)?

**Comment by Mikaz-fr** [comment]
Hi Alexey,

I do not know the softwares you are talking about. This package is for Sublime Text.
But as for Sublime Text I believe that the complexity for making a syntax highlighter will depend on the complexity of the language you are trying to cover.

Let me know if you have any issue with the package.

**Comment by Alexey-T** [comment]
Thanks for answer.It is text editor on uvviewsoft.com (so I guess you dont need it)
